### ISSUE TITLE
Test doesn't belong here - should be in another file (or a duplicate) 

### ISSUE THREAD

**Issue by kirshamir** [TewodrosHovagen/Maze#10]
https://github.com/TewodrosHovagen/Maze/blob/ffd4928c442337e2d97821dbebb23ce11054053a/src/test/java/maze/gameManager/GameManagerValidParameterizedImplTest.java#L71

**Comment by TewodrosHovagen** [comment]
@sagimiz

**Comment by TewodrosHovagen** [comment]
ask amir
