### ISSUE TITLE
Bad API: GameManager.addBookmark with seq value

### ISSUE THREAD

**Issue by kirshamir** [TewodrosHovagen/Maze#2]
https://github.com/TewodrosHovagen/Maze/blob/ffd4928c442337e2d97821dbebb23ce11054053a/src/test/java/maze/gameManager/GameManagerImplTest.java#L25

Bad API: addBookmark with seq value, better have seq value as running number inside GameManager

**Comment by TewodrosHovagen** [comment]
@sagimiz
