### ISSUE TITLE
Test - better test public API and not fields

### ISSUE THREAD

**Issue by kirshamir** [TewodrosHovagen/Maze#3]
https://github.com/TewodrosHovagen/Maze/blob/ffd4928c442337e2d97821dbebb23ce11054053a/src/test/java/maze/gameManager/GameManagerImplTest.java#L28

Should better ask GameManager for bookmark by point and see that you get the correct bookmark, checking directly a field is not a good practice

**Comment by TewodrosHovagen** [comment]
@sagimiz
