### ISSUE TITLE
WRONG - this method was not defined on the API of player, if it exist it is INTERNAL and cannot be called from GameManager!!

### ISSUE THREAD

**Issue by kirshamir** [TewodrosHovagen/Maze#34]
https://github.com/TewodrosHovagen/Maze/blob/ffd4928c442337e2d97821dbebb23ce11054053a/src/main/java/maze/gameManager/GameManagerImpl.java#L70

Player.setHitWall(false) -- no such public API in Player!

**Comment by TewodrosHovagen** [comment]
irrelevant
