### ISSUE TITLE
Might be easier to hold the prev location and just set back to the prev location

### ISSUE THREAD

**Issue by kirshamir** [TewodrosHovagen/Maze#35]
https://github.com/TewodrosHovagen/Maze/blob/ffd4928c442337e2d97821dbebb23ce11054053a/src/main/java/maze/gameManager/GameManagerImpl.java#L67

**Comment by TewodrosHovagen** [comment]
@TewodrosHovagen

**Comment by TewodrosHovagen** [comment]
fixed
