### ISSUE TITLE
Massive code duplications - consult how to do it in a nicer and simpler way!

### ISSUE THREAD

**Issue by kirshamir** [TewodrosHovagen/Maze#36]
https://github.com/TewodrosHovagen/Maze/blob/ffd4928c442337e2d97821dbebb23ce11054053a/src/main/java/maze/gameManager/GameManagerImpl.java#L159

**Comment by TewodrosHovagen** [comment]
change the enum and add values to change player location.

**Comment by TewodrosHovagen** [comment]
@TewodrosHovagen

**Comment by TewodrosHovagen** [comment]
fixed
