### ISSUE TITLE
Create the FileInputStream in a separate line then the BufferedReader - to get auto close on both

### ISSUE THREAD

**Issue by kirshamir** [TewodrosHovagen/Maze#37]
https://github.com/TewodrosHovagen/Maze/blob/ffd4928c442337e2d97821dbebb23ce11054053a/src/main/java/maze/fileDataParse/FileParse.java#L47

**Comment by TewodrosHovagen** [comment]
@sagimiz

**Comment by sagimiz** [comment]
Done
