### ISSUE TITLE
Can be rewritten without code duplication

### ISSUE THREAD

**Issue by kirshamir** [TewodrosHovagen/Maze#38]
https://github.com/TewodrosHovagen/Maze/blob/ffd4928c442337e2d97821dbebb23ce11054053a/src/main/java/maze/fileDataParse/FileParse.java#L86

**Comment by TewodrosHovagen** [comment]
@TewodrosHovagen

**Comment by TewodrosHovagen** [comment]
fixed

**Comment by TewodrosHovagen** [comment]
fixed
