### ISSUE TITLE
Test - no need for parameterized if you always pass the same value

### ISSUE THREAD

**Issue by kirshamir** [TewodrosHovagen/Maze#6]
https://github.com/TewodrosHovagen/Maze/blob/ffd4928c442337e2d97821dbebb23ce11054053a/src/test/java/maze/gameManager/GameManagerNonValidParameterizedImplTest.java#L20

Passing always: false, false for these two parameters

(and test is a bit naive)

**Comment by TewodrosHovagen** [comment]
@sagimiz
