### ISSUE TITLE
Bad test - shouldn't be able to add bookmark on wall or treasure (or at least no need to support that)

### ISSUE THREAD

**Issue by kirshamir** [TewodrosHovagen/Maze#9]
https://github.com/TewodrosHovagen/Maze/blob/ffd4928c442337e2d97821dbebb23ce11054053a/src/test/java/maze/gameManager/GameManagerValidParameterizedImplTest.java#L82

Test tries to set a bookmark on location of wall / treasure.
This behavior is not required.
Testing this is irrelevant.

**Comment by TewodrosHovagen** [comment]
@sagimiz
